# Generated by Django 2.1.5 on 2020-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pureDjangoApi', '0003_remove_pureapi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pureapi',
            name='Address',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
